# Generated by Django 5.2.9 on 2026-01-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="License key in format XXXX-XXXX-XXXX-XXXX",
                        max_length=19,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                        ],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Hashed device identifier",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        help_text="SHA-256 hash of hardware fingerprint", max_length=64
                    ),
                ),
                (
                    "mac_address_hash",
                    models.CharField(
                        help_text="SHA-256 hash of MAC address", max_length=64
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-activated_at"],
            },
        ),
    ]
